---
permalink: online-help/concept-how-storage-qos-can-control-workload-throughput.html 
sidebar: sidebar 
keywords:  
summary: 'È possibile creare o modificare un gruppo di criteri QoS per controllare il limite di i/o al secondo (IOPS) o throughput (Mbps) per i carichi di lavoro in esso contenuti. Se i carichi di lavoro si trovano in un gruppo di policy senza limiti impostati, ad esempio il gruppo di policy predefinito, o se il limite impostato non soddisfa le esigenze, è possibile aumentare il limite o spostare i carichi di lavoro in un gruppo di policy nuovo o esistente con il limite desiderato.' 
---
= In che modo la QoS dello storage può controllare il throughput dei carichi di lavoro
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare o modificare un gruppo di criteri QoS (Quality of Service) per controllare il limite di i/o al secondo (IOPS) o di throughput (Mbps) per i carichi di lavoro in esso contenuti. Se i carichi di lavoro si trovano in un gruppo di policy senza limiti impostati, ad esempio il gruppo di policy predefinito, o se il limite impostato non soddisfa le esigenze, è possibile aumentare il limite o spostare i carichi di lavoro in un gruppo di policy nuovo o esistente con il limite desiderato.

I gruppi di policy QoS "`standard`" possono essere assegnati a singoli carichi di lavoro, ad esempio un singolo volume o LUN. In questo caso, il carico di lavoro può utilizzare il limite di throughput completo. I gruppi di policy di QoS possono anche essere assegnati a più carichi di lavoro, nel qual caso il limite di throughput viene condiviso tra i carichi di lavoro. Ad esempio, un limite di QoS di 9,000 IOPS assegnati a tre carichi di lavoro limiterebbe gli IOPS combinati a superare 9,000 IOPS.

I gruppi di policy QoS "`Adaptive`" possono essere assegnati anche a singoli carichi di lavoro o a più carichi di lavoro. Tuttavia, anche se assegnato a più carichi di lavoro, ogni carico di lavoro ottiene il limite massimo di throughput invece di condividere il valore di throughput con altri carichi di lavoro. Inoltre, le policy QoS adattive regolano automaticamente l'impostazione del throughput in base alle dimensioni del volume, per ogni carico di lavoro, mantenendo così il rapporto tra IOPS e terabyte al variare delle dimensioni del volume. Ad esempio, se il picco è impostato su 5,000 IOPS/TB nella policy QoS adattiva, un volume da 10 TB avrà un limite di throughput di 50,000 IOPS. Se il volume viene ridimensionato successivamente a 20 TB, la QoS adattiva regola il tetto a 100,000 IOPS.

A partire da ONTAP 9.5, è possibile includere le dimensioni del blocco quando si definisce un criterio QoS adattivo. In questo modo, la policy viene convertita da una soglia IOPS/TB a una soglia Mbps per i casi in cui i carichi di lavoro utilizzano blocchi di dimensioni molto grandi e, in ultima analisi, utilizzano una grande percentuale di throughput.

Per le policy QoS di gruppo condiviso, quando gli IOPS o i Mbps di tutti i carichi di lavoro in un gruppo di policy superano il limite impostato, il gruppo di policy limita i carichi di lavoro per limitare la loro attività, riducendo così le performance di tutti i carichi di lavoro nel gruppo di policy. Se un evento di performance dinamica viene generato dalla limitazione del gruppo di criteri, la descrizione dell'evento visualizza il nome del gruppo di criteri interessato.

Nella pagina Performance/Volumes Inventory (inventario performance/volumi), è possibile ordinare i volumi interessati in base a IOPS e Mbps per vedere quali carichi di lavoro hanno il massimo utilizzo che potrebbe aver contribuito all'evento. Nella pagina Performance/Volumes Explorer (Esplora prestazioni/volumi), è possibile selezionare altri volumi o LUN da confrontare con l'utilizzo del throughput IOPS o Mbps del carico di lavoro interessato.

Assegnando i carichi di lavoro che stanno utilizzando in eccesso le risorse del nodo a un'impostazione di gruppo di policy più restrittiva, il gruppo di policy limita i carichi di lavoro per limitare la loro attività, riducendo così l'utilizzo delle risorse su quel nodo. Tuttavia, se si desidera che il carico di lavoro sia in grado di utilizzare più risorse del nodo, è possibile aumentare il valore del gruppo di criteri.

È possibile utilizzare Gestione sistema o i comandi ONTAP per gestire i gruppi di criteri, incluse le seguenti attività:

* Creazione di un gruppo di criteri
* Aggiunta o rimozione di workload in un gruppo di policy
* Spostamento di un workload tra gruppi di policy
* Modifica del limite di throughput di un gruppo di criteri
* Spostamento di un workload in un aggregato e/o nodo diverso

