---
permalink: online-help/concept-how-scripts-work-with-alerts.html 
sidebar: sidebar 
keywords:  
summary: È possibile associare un avviso allo script in modo che venga eseguito quando viene generato un avviso per un evento in Unified Manager. È possibile utilizzare gli script per risolvere i problemi relativi agli oggetti di storage o identificare gli oggetti di storage che generano gli eventi. 
---
= Come funzionano gli script con gli avvisi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile associare un avviso allo script in modo che venga eseguito quando viene generato un avviso per un evento in Unified Manager. È possibile utilizzare gli script per risolvere i problemi relativi agli oggetti di storage o identificare gli oggetti di storage che generano gli eventi.

Quando viene generato un avviso per un evento in Unified Manager, viene inviata un'email di avviso ai destinatari specificati. Se è stato associato un avviso a uno script, lo script viene eseguito. È possibile ottenere i dettagli degli argomenti passati allo script dall'e-mail di avviso.

Lo script utilizza i seguenti argomenti per l'esecuzione:

* -`eventID`
* -`eventName`
* -`eventSeverity`
* -`eventSourceID`
* -`eventSourceName`
* -`eventSourceType`
* -`eventState`
* -`eventArgs`


È possibile utilizzare gli argomenti negli script e raccogliere informazioni relative agli eventi o modificare gli oggetti di storage.



== Esempio per ottenere argomenti dagli script

[listing]
----
print "$ARGV[0] : $ARGV[1]\n"
print "$ARGV[7] : $ARGV[8]\n"
----
Quando viene generato un avviso, questo script viene eseguito e viene visualizzato il seguente output:

[listing]
----
-eventID : 290
-eventSourceID : 4138
----