---
permalink: online-help/reference-aggregate-thresholds-page.html 
sidebar: sidebar 
keywords:  
summary: 'La pagina Configuration/Health Thresholds (soglie di configurazione/integrità) per gli aggregati consente di configurare i valori delle soglie di integrità globali per gli aggregati monitorati. Quando si configurano le opzioni a livello globale, i valori predefiniti di tutti gli oggetti vengono modificati. Tuttavia, se i valori predefiniti sono stati modificati a livello di oggetto, i valori globali non vengono modificati.' 
---
= Pagina delle soglie di configurazione/integrità per gli aggregati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La pagina Configuration/Health Thresholds (soglie di configurazione/integrità) per gli aggregati consente di configurare i valori delle soglie di integrità globali per gli aggregati monitorati. Quando si configurano le opzioni a livello globale, i valori predefiniti di tutti gli oggetti vengono modificati. Tuttavia, se i valori predefiniti sono stati modificati a livello di oggetto, i valori globali non vengono modificati.

È necessario disporre del ruolo di amministratore dello storage o amministratore dello storage di OnCommand.

Gli eventi vengono generati in caso di superamento di una soglia. È possibile intraprendere azioni correttive per tali eventi.

I valori di soglia non sono applicabili all'aggregato root del nodo.

È possibile impostare soglie di integrità aggregate per: Capacità, crescita aggregata e copie Snapshot aggregate.



== Area di capacità

L'area Capacity (capacità) consente di impostare le seguenti condizioni di soglia della capacità aggregata. Si noti che quando la funzione di crescita automatica è attivata sui volumi che risiedono nell'aggregato, le soglie della capacità aggregata vengono considerate violate in base alle dimensioni massime del volume impostate dalla funzione di crescita automatica, non in base alle dimensioni originali del volume.

* *Spazio quasi pieno*
+
Specifica la percentuale in cui un aggregato viene considerato quasi pieno:

+
** Valore predefinito: 80 percento
+
Il valore di questa soglia deve essere inferiore al valore della soglia completa aggregata per consentire al server di gestione di generare un evento.

** Evento generato: Aggregato quasi pieno
** Severità dell'evento: Avviso


* *Spazio pieno*
+
Specifica la percentuale in cui un aggregato viene considerato pieno:

+
** Valore predefinito: 90 percento
** Evento generato: Aggregato pieno
** Severità evento: Errore


* *Quasi impegnato*
+
Specifica la percentuale in cui un aggregato viene considerato quasi overcommit:

+
** Valore predefinito: 95 percento
+
Il valore di questa soglia deve essere inferiore al valore della soglia aggregata Overcommit Full per il server di gestione per generare un evento.

** Evento generato: Aggregato quasi in eccesso
** Severità dell'evento: Avviso


* *Impegnato in eccesso*
+
Specifica la percentuale in cui un aggregato viene considerato come overcommit:

+
** Valore predefinito: 100 percento
** Evento generato: Aggregato con overcommit
** Severità evento: Errore


* *Giorni fino al completo*
+
Specifica il numero di giorni rimanenti prima che l'aggregato raggiunga la capacità completa:

+
** Valore predefinito: 7
** Evento generato: Giorni aggregati fino al pieno
** Severità evento: Errore






== Area di crescita

L'area di crescita consente di impostare le seguenti condizioni di soglia per la crescita aggregata:

* *Tasso di crescita*
+
Specifica la percentuale in cui il tasso di crescita di un aggregato viene considerato normale prima che il sistema generi un evento anomalo di tasso di crescita aggregato:

+
** Valore predefinito: 1 percento
** Evento generato: Tasso di crescita aggregato anomalo
** Severità dell'evento: Avviso


* *Growth Rate Sensitivity*
+
Specifica il fattore applicato alla deviazione standard del tasso di crescita di un aggregato. Se il tasso di crescita supera la deviazione standard fattorizzata, viene generato un evento aggregato di tasso di crescita anomalo.

+
Un valore inferiore per la sensibilità del tasso di crescita indica che l'aggregato è altamente sensibile alle variazioni del tasso di crescita. L'intervallo per la sensibilità del tasso di crescita è compreso tra 1 e 5.

+
** Valore predefinito: 2


+
[NOTE]
====
Se si modifica la sensibilità del tasso di crescita per gli aggregati al livello di soglia globale, la modifica viene applicata anche alla sensibilità del tasso di crescita per i volumi al livello di soglia globale.

====




== Area delle copie Snapshot

L'area Snapshot Copies (copie Snapshot) consente di impostare le seguenti condizioni di soglia Snapshot Reserve:

* *Snapshot Reserve Full*
+
Specifica la percentuale in cui un aggregato ha consumato tutto lo spazio riservato per le copie Snapshot:

+
** Valore predefinito: 90 percento
** Evento generato: Riserva Snapshot aggregata piena
** Severità dell'evento: Avviso






== Pulsanti di comando

* *Ripristina impostazioni predefinite*
+
Consente di ripristinare i valori predefiniti delle impostazioni di configurazione.

* *Salva*
+
Salva le impostazioni di configurazione per l'opzione selezionata.


