---
permalink: online-help/reference-add-annotation-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 'La finestra di dialogo Add Annotation (Aggiungi annotazione) consente di creare annotazioni personalizzate che è possibile associare a cluster, volumi e macchine virtuali di storage attraverso regole di annotazione.' 
---
= Finestra di dialogo Add Annotation (Aggiungi annotazione)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La finestra di dialogo Add Annotation (Aggiungi annotazione) consente di creare annotazioni personalizzate che è possibile associare a cluster, volumi e macchine virtuali di storage (SVM) attraverso regole di annotazione.

È necessario disporre del ruolo di amministratore dello storage o amministratore dello storage di OnCommand.

* *Nome annotazione*
+
Specifica il nome dell'annotazione. Immettere un nome univoco per l'annotazione.

* *Descrizione*
+
Specifica una descrizione significativa dell'annotazione.





== Valori di annotazione

* *Aggiungi*
+
Aggiunge un nuovo valore all'annotazione selezionata.

* *Elimina*
+
Elimina il valore selezionato per un'annotazione.





== Pulsanti di comando

* *Salva e chiudi*
+
Salva la nuova annotazione e chiude la finestra di dialogo Add Annotation (Aggiungi annotazione).

* *Annulla*
+
Chiude la finestra di dialogo Add Annotation (Aggiungi annotazione) senza salvare le modifiche.


