---
permalink: online-help/reference-resynchronize-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: La finestra di dialogo risincronizza consente di risincronizzare i dati su una relazione SnapMirror o SnapVault precedentemente interrotta e quindi la destinazione è stata creata come volume di lettura/scrittura. È inoltre possibile risincronizzare quando viene eliminata una copia Snapshot comune richiesta sul volume di origine, causando il mancato aggiornamento di SnapMirror o SnapVault. 
---
= Finestra di dialogo di risincronizzazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La finestra di dialogo risincronizza consente di risincronizzare i dati su una relazione SnapMirror o SnapVault precedentemente interrotta e quindi la destinazione è stata creata come volume di lettura/scrittura. È inoltre possibile risincronizzare quando viene eliminata una copia Snapshot comune richiesta sul volume di origine, causando il mancato aggiornamento di SnapMirror o SnapVault.



== Scheda Opzioni di risincronizzazione

La scheda Opzioni di risincronizzazione consente di impostare la priorità di trasferimento e la velocità di trasferimento massima per la relazione di protezione che si sta risincronizzando.

* *Priorità trasferimento*
+
La priorità di esecuzione del trasferimento. È possibile selezionare normale o basso. Relazioni con policy che specificano una normale priorità di trasferimento eseguite prima di quelle con policy che specificano una bassa priorità di trasferimento.

* *Velocità di trasferimento massima*
+
Specifica la velocità massima con cui i dati vengono trasferiti tra cluster sulla rete. Se selezionata, la larghezza di banda della rete è limitata al valore specificato. È possibile immettere un valore numerico e selezionare kilobyte per second (kbps), megabyte per second (Mbps), gigabyte per second (Gbps) o Tbps. Se si sceglie di non utilizzare una velocità di trasferimento massima, il trasferimento di riferimento tra le relazioni è illimitato. Tuttavia, se si utilizza ONTAP 8.2 e il cluster primario e secondario sono identici, questa impostazione viene disattivata.





== Scheda copie Snapshot di origine

La scheda Source Snapshot Copies (copie Snapshot di origine) visualizza le seguenti informazioni sulla copia Snapshot di origine utilizzata per il trasferimento di riferimento:

* *Volume di origine*
+
Visualizza i nomi dei volumi di origine corrispondenti.

* *Volume di destinazione*
+
Visualizza i nomi dei volumi di destinazione selezionati.

* *Tipo di origine*
+
Visualizza il tipo di volume: Lettura/scrittura o protezione dati.

* *Snapshot Copy*
+
Visualizza la copia Snapshot utilizzata per il trasferimento dei dati. Facendo clic sul valore della copia Snapshot viene visualizzata la finestra di dialogo Select Source Snapshot Copy (Seleziona copia Snapshot di origine), in cui è possibile selezionare una copia Snapshot specifica per il trasferimento, a seconda del tipo di relazione di protezione in uso e dell'operazione che si sta eseguendo.





== Pulsanti di comando

* *Invia*
+
Avvia il processo di risincronizzazione e chiude la finestra di dialogo risincronizzazione.

* *Annulla*
+
Annulla le selezioni e chiude la finestra di dialogo Risincronizza.


