---
permalink: online-help/reference-edit-group-action-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 'È possibile modificare l"azione di gruppo creata per i gruppi utilizzando la finestra di dialogo Modifica azione gruppo.' 
---
= Finestra di dialogo Edit Group Action (Modifica azione di gruppo)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare l'azione di gruppo creata per i gruppi utilizzando la finestra di dialogo Modifica azione gruppo.

È necessario disporre del ruolo di amministratore dello storage o amministratore dello storage di OnCommand.

* *Nome azione*
+
Visualizza il nome dell'azione di gruppo.

* *Descrizione*
+
Visualizza la descrizione dell'azione di gruppo.

* *Gruppo*
+
Visualizza il nome del gruppo selezionato.

* *Tipo di azione*
+
Visualizza il tipo di azione di gruppo. Non è possibile modificare il tipo di azione. Tuttavia, è possibile modificare i parametri utilizzati per configurare l'azione di gruppo.





== Pulsanti di comando

* *Salva*
+
Salva le modifiche apportate all'azione di gruppo.

* *Annulla*
+
Chiude la finestra di dialogo Modifica azione gruppo senza salvare le modifiche.


