---
permalink: online-help/task-initializing-or-updating-protection-relationships-from-the-health-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: È possibile eseguire un primo trasferimento baseline su una nuova relazione di protezione o aggiornare una relazione se è già inizializzata e si desidera eseguire un aggiornamento incrementale manuale e non pianificato per trasferire immediatamente i dati. 
---
= Inizializzazione o aggiornamento delle relazioni di protezione dalla pagina Health/Volume Details
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire un primo trasferimento baseline su una nuova relazione di protezione o aggiornare una relazione se è già inizializzata e si desidera eseguire un aggiornamento incrementale manuale e non pianificato per trasferire immediatamente i dati.



== Prima di iniziare

* È necessario disporre del ruolo di amministratore dello storage o amministratore dello storage di OnCommand.
* È necessario aver configurato OnCommand Workflow Automation.




== Fasi

. Dalla scheda *Protection* della pagina dei dettagli *Health/Volume*, individuare nella topologia la relazione di protezione che si desidera inizializzare o aggiornare, quindi fare clic con il pulsante destro del mouse.
. Selezionare *Inizializza/Aggiorna* dal menu.
+
In alternativa, dal menu *azioni*, selezionare *relazione* > *Inizializza/Aggiorna* per inizializzare o aggiornare la relazione per la quale si stanno visualizzando i dettagli.

+
Viene visualizzata la finestra di dialogo Inizializza/Aggiorna.

. Nella scheda *Opzioni di trasferimento*, selezionare una priorità di trasferimento e la velocità di trasferimento massima.
. Fare clic su *Source Snapshot Copies*, quindi nella colonna *Snapshot Copy*, fare clic su *Default*.
+
Viene visualizzata la finestra di dialogo Select Source Snapshot Copy (Seleziona copia snapshot di origine).

. Se si desidera specificare una copia Snapshot esistente invece di trasferire la copia Snapshot predefinita, fare clic su *Existing Snapshot Copy* (Copia istantanea esistente) e selezionare una copia Snapshot dall'elenco.
. Fare clic su *Invia*.
+
Viene visualizzata nuovamente la finestra di dialogo Inizializza/Aggiorna.

. Se sono state selezionate più origini da inizializzare o aggiornare, fare clic su *Default* per la successiva origine di lettura/scrittura per la quale si desidera specificare una copia Snapshot esistente.
+
Non è possibile selezionare una copia Snapshot diversa per i volumi di protezione dei dati.

. Fare clic su *Submit* (Invia) per avviare il processo di inizializzazione o aggiornamento.
+
Il processo di inizializzazione o aggiornamento viene avviato, viene visualizzata nuovamente la pagina Health/Volume Details (Dettagli stato/volume) e viene visualizzato un collegamento ai processi nella parte superiore della pagina.

. Fare clic su *View Jobs* (Visualizza processi) nella pagina dei dettagli *Health/Volume* per tenere traccia dello stato di ogni processo di inizializzazione o di aggiornamento.
+
Viene visualizzato un elenco filtrato di lavori.

. Fare clic su ciascun lavoro per visualizzarne i dettagli.
. Fare clic sulla freccia Indietro del browser per tornare alla pagina dei dettagli *Health/Volume*.
+
L'operazione di inizializzazione o aggiornamento viene completata al termine di tutte le attività del lavoro.


