---
permalink: online-help/task-editing-protection-relationships-from-the-protection-volume-relationships-page.html 
sidebar: sidebar 
keywords:  
summary: È possibile modificare le relazioni di protezione esistenti per modificare la velocità di trasferimento massima, la policy di protezione o la pianificazione della protezione. È possibile modificare una relazione per ridurre la larghezza di banda utilizzata per i trasferimenti o per aumentare la frequenza dei trasferimenti pianificati perché i dati cambiano spesso. 
---
= Modifica delle relazioni di protezione dalla pagina delle relazioni protezione/volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare le relazioni di protezione esistenti per modificare la velocità di trasferimento massima, la policy di protezione o la pianificazione della protezione. È possibile modificare una relazione per ridurre la larghezza di banda utilizzata per i trasferimenti o per aumentare la frequenza dei trasferimenti pianificati perché i dati cambiano spesso.



== Prima di iniziare

È necessario disporre del ruolo di amministratore dello storage o amministratore dello storage di OnCommand.



== A proposito di questa attività

I volumi selezionati devono essere destinazioni delle relazioni di protezione. Non è possibile modificare le relazioni quando sono selezionati volumi di origine, volumi di condivisione del carico o volumi che non sono la destinazione di una relazione SnapMirror o SnapVault.



== Fasi

. Nella pagina *Relazioni protezione/volume*, selezionare nell'elenco volumi uno o più volumi nella stessa SVM per cui si desidera modificare le impostazioni di relazione, quindi selezionare *Modifica* dalla barra degli strumenti.
+
Viene visualizzata la finestra di dialogo Edit Relationship (Modifica relazione).

. Nella finestra di dialogo *Edit Relationship* (Modifica relazione), modificare la velocità di trasferimento massima, la policy di protezione o la pianificazione di protezione, in base alle necessità.
. Fare clic su *Apply* (Applica).
+
Le modifiche vengono applicate alle relazioni selezionate.


