---
permalink: online-help/task-resynchronizing-protection-relationships.html 
sidebar: sidebar 
keywords:  
summary: 'Dalla pagina Protection/Volume Relationship (Relazioni protezione/volume), è possibile risincronizzare una relazione per eseguire il ripristino da un evento che ha disattivato il volume di origine o quando si desidera modificare l"origine corrente in un volume diverso.' 
---
= Risincronizzazione delle relazioni di protezione dalla pagina delle relazioni protezione/volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dalla pagina Protection/Volume Relationship (Relazioni protezione/volume), è possibile risincronizzare una relazione per eseguire il ripristino da un evento che ha disattivato il volume di origine o quando si desidera modificare l'origine corrente in un volume diverso.



== Prima di iniziare

* È necessario disporre del ruolo di amministratore dello storage o amministratore dello storage di OnCommand.
* È necessario aver impostato l'automazione del flusso di lavoro.




== Fasi

. Dalla pagina *Relazioni protezione/volume*, selezionare uno o più volumi con relazioni in modalità di disattivazione e, dalla barra degli strumenti, fare clic su *Risincronizza*.
+
Viene visualizzata la finestra di dialogo risincronizza.

. Nella scheda *Opzioni di risincronizzazione*, selezionare una priorità di trasferimento e la velocità di trasferimento massima.
. Fare clic su *Source Snapshot Copies*, quindi nella colonna *Snapshot Copy*, fare clic su *Default*.
+
Viene visualizzata la finestra di dialogo Select Source Snapshot Copy (Seleziona copia snapshot di origine).

. Se si desidera specificare una copia Snapshot esistente invece di trasferire la copia Snapshot predefinita, fare clic su *Existing Snapshot Copy* (Copia istantanea esistente) e selezionare una copia Snapshot dall'elenco.
. Fare clic su *Invia*.
+
Viene visualizzata nuovamente la finestra di dialogo risincronizza.

. Se sono state selezionate più origini da risincronizzare, fare clic su *Default* per l'origine successiva per la quale si desidera specificare una copia Snapshot esistente.
. Fare clic su *Submit* (Invia) per avviare il processo di risincronizzazione.
+
Viene avviato il processo di risincronizzazione, viene visualizzata la pagina delle relazioni protezione/volume e nella parte superiore della pagina viene visualizzato un collegamento ai lavori.

. Fare clic su *View Jobs* (Visualizza processi) nella pagina *Protection/Volume Religation* (Relazioni di protezione/volume) per tenere traccia dello stato di ciascun processo di risincronizzazione.
+
Viene visualizzato un elenco filtrato di lavori.

. Fare clic sulla freccia *Indietro* del browser per tornare alla pagina *protezione/Relazioni volume*.
+
L'operazione di risincronizzazione è terminata al termine di tutte le attività del lavoro.


