---
permalink: online-help/task-exporting-a-data-policy-configuration.html 
sidebar: sidebar 
keywords:  
summary: È possibile esportare una configurazione dei criteri dati da Unified Manager in un file. Ad esempio, dopo aver eseguito il backup richiesto e in caso di disastro, è possibile esportare la configurazione del criterio dati dal server primario. 
---
= Esportazione di una configurazione di policy dei dati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile esportare una configurazione dei criteri dati da Unified Manager in un file. Ad esempio, dopo aver eseguito il backup richiesto e in caso di disastro, è possibile esportare la configurazione del criterio dati dal server primario.



== Prima di iniziare

È necessario disporre del ruolo di amministratore dello storage o amministratore dello storage di OnCommand.



== A proposito di questa attività

La scheda Data Policy (Policy dati), utilizzata durante l'esecuzione di questa attività, viene visualizzata solo per le SVM con Infinite Volume.



== Fasi

. Nel riquadro di navigazione a sinistra, fare clic su *Health* > *SVM*.
. Nella pagina di inventario *Health/Storage Virtual Machines*, selezionare la SVM appropriata.
. Fare clic su *Data Policy*.
+
Viene visualizzato l'elenco delle regole nella policy dei dati per la SVM selezionata con volume infinito.

. Fare clic su *Esporta*.
. Nella finestra di dialogo specifica del browser, specificare la posizione in cui esportare la configurazione del criterio dati.




== Risultati

La configurazione del criterio dati viene esportata come file JSON nella posizione specificata.
