---
permalink: online-help/task-moving-workloads-to-a-different-aggregate.html 
sidebar: sidebar 
keywords:  
summary: 'È possibile utilizzare Unified Manager per identificare un aggregato meno occupato rispetto all"aggregato in cui risiedono attualmente i carichi di lavoro, quindi è possibile spostare volumi o LUN selezionati in tale aggregato. Lo spostamento di carichi di lavoro dalle performance elevate in un aggregato meno occupato o in un aggregato con storage flash abilitato consente al carico di lavoro di funzionare in modo più efficiente.' 
---
= Spostamento dei carichi di lavoro in un aggregato diverso
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare Unified Manager per identificare un aggregato meno occupato rispetto all'aggregato in cui risiedono attualmente i carichi di lavoro, quindi è possibile spostare volumi o LUN selezionati in tale aggregato. Lo spostamento di carichi di lavoro dalle performance elevate in un aggregato meno occupato o in un aggregato con storage flash abilitato consente al carico di lavoro di funzionare in modo più efficiente.



== Prima di iniziare

* È necessario disporre del ruolo di operatore, amministratore OnCommand o amministratore dello storage.
* È necessario aver registrato il nome dell'aggregato che ha attualmente un problema di performance.
* È necessario aver registrato la data e l'ora in cui l'aggregato ha ricevuto l'evento.
* È necessario aver registrato l'ID dell'evento, ad esempio"` p-sdt-clus1-ag-2542`".
* Unified Manager deve aver raccolto e analizzato almeno un mese di dati relativi alle performance.




== A proposito di questa attività

Questi passaggi ti aiutano a identificare le seguenti risorse in modo da poter spostare i carichi di lavoro dalle performance elevate verso un aggregato meno utilizzato:

* Gli aggregati sullo stesso cluster meno utilizzati
* I volumi dalle performance più elevate dell'aggregato corrente




== Fasi

. Identificare l'aggregato nel cluster meno utilizzato:
+
.. Nella pagina dei dettagli *evento*, fare clic sul nome del cluster in cui risiede l'aggregato.
+
I dettagli del cluster vengono visualizzati nella pagina Landing di Performance/Cluster.

.. Nella pagina *Riepilogo*, fare clic su *aggregati* dal riquadro *oggetti gestiti*.
+
Viene visualizzato l'elenco degli aggregati in questo cluster.

.. Fare clic sulla colonna *Utilization* (utilizzo) per ordinare gli aggregati in base al minor utilizzo.
+
È inoltre possibile identificare gli aggregati che hanno la capacità massima * libera*. In questo modo viene fornito un elenco di potenziali aggregati in cui è possibile spostare i carichi di lavoro.

.. Annotare il nome dell'aggregato in cui si desidera spostare i carichi di lavoro.


. Identificare i volumi dalle performance elevate dell'aggregato che ha ricevuto l'evento:
+
.. Fare clic sull'aggregato che presenta problemi di performance.
+
I dettagli dell'aggregato vengono visualizzati nella pagina Performance/aggregate Explorer (Esplora prestazioni/aggregato).

.. Dal selettore *intervallo di tempo*, selezionare *ultimi 30 giorni*, quindi fare clic su *Applica intervallo*.
+
In questo modo è possibile visualizzare una cronologia delle performance più lunga rispetto alle 72 ore predefinite. Si desidera spostare un volume che utilizza molte risorse in modo coerente, non solo nelle ultime 72 ore.

.. Dal controllo *View and compare*, selezionare *Volumes on this aggregate* (volumi su questo aggregato).
+
Viene visualizzato un elenco di volumi FlexVol e volumi FlexGroup costitutivi su questo aggregato.

.. Ordinare i volumi in base ai Mbps più elevati, quindi in base agli IOPS più elevati, per visualizzare i volumi con le performance più elevate.
.. Annotare i nomi dei volumi che si desidera spostare in un aggregato diverso.


. Sposta i volumi dalle performance elevate nell'aggregato identificato come a basso utilizzo.
+
È possibile eseguire l'operazione di spostamento utilizzando Gestione sistema di OnCommand, OnCommand Workflow Automation, comandi ONTAP o una combinazione di questi strumenti.





== Al termine

Dopo alcuni giorni, verificare se si stanno ricevendo lo stesso tipo di eventi da questo nodo o aggregato.
