---
permalink: online-help/task-reversing-protection-relationships.html 
sidebar: sidebar 
keywords:  
summary: 'Quando un disastro disattiva il volume di origine nella relazione di protezione, è possibile utilizzare il volume di destinazione per fornire i dati convertendolo in un volume di lettura/scrittura durante la riparazione o la sostituzione dell"origine. Quando l"origine è nuovamente disponibile per ricevere i dati, è possibile utilizzare l"operazione di risincronizzazione inversa per stabilire la relazione nella direzione inversa, sincronizzando i dati sull"origine con i dati sulla destinazione di lettura/scrittura.' 
---
= Invertire le relazioni di protezione dalla pagina delle relazioni protezione/volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando un disastro disattiva il volume di origine nella relazione di protezione, è possibile utilizzare il volume di destinazione per fornire i dati convertendolo in un volume di lettura/scrittura durante la riparazione o la sostituzione dell'origine. Quando l'origine è nuovamente disponibile per ricevere i dati, è possibile utilizzare l'operazione di risincronizzazione inversa per stabilire la relazione nella direzione inversa, sincronizzando i dati sull'origine con i dati sulla destinazione di lettura/scrittura.



== Prima di iniziare

* È necessario disporre del ruolo di amministratore dello storage o amministratore dello storage di OnCommand.
* È necessario aver impostato l'automazione del flusso di lavoro.
* La relazione non deve essere una relazione SnapVault.
* Una relazione di protezione deve già esistere.
* Il rapporto di protezione deve essere interrotto.
* Sia l'origine che la destinazione devono essere in linea.
* L'origine non deve essere la destinazione di un altro volume di protezione dei dati.




== A proposito di questa attività

* Quando si esegue questa attività, i dati sull'origine più recenti dei dati sulla copia Snapshot comune vengono cancellati.
* Le policy e le pianificazioni create sulle relazioni di risincronizzazione inversa sono le stesse della relazione di protezione originale.
+
Se le policy e le pianificazioni non esistono, vengono create.





== Fasi

. Dalla pagina *Relazioni protezione/volume*, selezionare uno o più volumi con relazioni da invertire e, sulla barra degli strumenti, fare clic su *Risincronizzazione inversa*.
+
Viene visualizzata la finestra di dialogo Reverse Resync (risincronizzazione inversa).

. Verificare che le relazioni visualizzate nella finestra di dialogo *Reverse Resync* siano quelle per le quali si desidera eseguire l'operazione di risincronizzazione inversa, quindi fare clic su *Submit* (Invia).
+
Viene avviata l'operazione di risincronizzazione inversa, viene visualizzata nuovamente la pagina delle relazioni protezione/volume e nella parte superiore della pagina viene visualizzato un collegamento ai lavori.

. Fare clic su *View Jobs* (Visualizza processi) nella pagina *Protection/Volume Religation* (Relazioni protezione/volume) per tenere traccia dello stato di ciascun processo di risincronizzazione inversa.
+
Viene visualizzato un elenco filtrato di lavori correlati a questa operazione.

. Fare clic sulla freccia *Indietro* del browser per tornare alla pagina *protezione/Relazioni volume*.
+
L'operazione di risincronizzazione inversa viene completata al termine di tutte le attività del lavoro.


