---
permalink: online-help/task-aborting-an-active-data-protection-transfer.html 
sidebar: sidebar 
keywords:  
summary: 'È possibile interrompere un trasferimento di protezione dei dati attivo quando si desidera interrompere una replica SnapMirror in corso. È inoltre possibile cancellare il checkpoint di riavvio per i trasferimenti successivi al trasferimento di riferimento. È possibile interrompere un trasferimento in caso di conflitto con un"altra operazione, ad esempio uno spostamento del volume.' 
---
= Interruzione di un trasferimento di protezione dei dati attivo dalla pagina delle relazioni protezione/volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile interrompere un trasferimento di protezione dei dati attivo quando si desidera interrompere una replica SnapMirror in corso. È inoltre possibile cancellare il checkpoint di riavvio per i trasferimenti successivi al trasferimento di riferimento. È possibile interrompere un trasferimento in caso di conflitto con un'altra operazione, ad esempio uno spostamento del volume.



== Prima di iniziare

* È necessario disporre del ruolo di amministratore dello storage o amministratore dello storage di OnCommand.
* È necessario aver impostato l'automazione del flusso di lavoro.




== A proposito di questa attività

L'azione di interruzione non viene visualizzata nei seguenti casi:

* Se le impostazioni RBAC non consentono questa azione: Ad esempio, se si dispone solo di privilegi operatore
* Quando l'ID del volume è sconosciuto: Ad esempio, quando si dispone di una relazione tra cluster e il cluster di destinazione non è stato ancora rilevato


Non è possibile cancellare il checkpoint di riavvio per un trasferimento di riferimento.



== Fasi

. Per interrompere i trasferimenti per una o più relazioni di protezione, dalla pagina *protezione/Relazioni volume*, selezionare uno o più volumi e, sulla barra degli strumenti, fare clic su *Interrompi*.
+
Viene visualizzata la finestra di dialogo Interrompi trasferimento.

. Se si desidera cancellare il checkpoint di riavvio per un trasferimento che non è un trasferimento di riferimento, selezionare *Clear Checkpoint*.
. Fare clic su *continua*.
+
La finestra di dialogo Interrompi trasferimento viene chiusa e lo stato del processo di interruzione viene visualizzato nella parte superiore della pagina delle relazioni protezione/volume, insieme a un collegamento ai dettagli del processo.

. Fare clic sul collegamento *View details* (Visualizza dettagli) per accedere alla pagina *Protection/Job* Details (Dettagli protezione/lavoro) per ulteriori dettagli e per visualizzare l'avanzamento del lavoro.

