---
permalink: online-help/task-resuming-scheduled-transfers-on-a-quiesced-relationship.html 
sidebar: sidebar 
keywords:  
summary: Dopo aver interrotto una relazione per impedire il verificarsi di trasferimenti pianificati, è possibile utilizzare Riprendi per riabilitare i trasferimenti pianificati in modo da proteggere i dati sul volume primario o di origine. I trasferimenti vengono ripristinati da un checkpoint, se presente, al successivo intervallo di trasferimento pianificato. 
---
= Ripresa dei trasferimenti pianificati su una relazione a cui è stata data la disattivazione dalla pagina Protection/Volume Relationship (rapporti protezione/volume)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver interrotto una relazione per impedire il verificarsi di trasferimenti pianificati, è possibile utilizzare *Riprendi* per riabilitare i trasferimenti pianificati in modo da proteggere i dati sul volume primario o di origine. I trasferimenti vengono ripristinati da un checkpoint, se presente, al successivo intervallo di trasferimento pianificato.



== Prima di iniziare

* È necessario disporre del ruolo di amministratore dello storage o amministratore dello storage di OnCommand.
* È necessario aver impostato l'automazione del flusso di lavoro.




== A proposito di questa attività

È possibile selezionare non più di 10 relazioni in cui riprendere i trasferimenti.



== Fasi

. Dalla pagina *Relazioni protezione/volume*, selezionare uno o più volumi con relazioni in modalità di disattivazione e, sulla barra degli strumenti, fare clic su *Riprendi*.
. Nella finestra di dialogo *Riprendi*, fare clic su *continua*.
+
Viene visualizzata nuovamente la pagina Protection/Volume Relrelazione.

. Per visualizzare le attività di lavoro correlate e monitorarne l'avanzamento, fare clic sul collegamento al lavoro visualizzato nella parte superiore della pagina *protezione/Relazioni volumi*.
. Effettuare una delle seguenti operazioni:
+
** Se viene visualizzato un solo lavoro, nella pagina protezione/Dettagli lavoro fare clic su *Aggiorna* per aggiornare l'elenco delle attività e i dettagli delle attività associati al lavoro di configurazione della protezione e per determinare quando il lavoro è completo.
** Se viene visualizzato più di un lavoro,
+
... Nella pagina protezione/lavori, fare clic sul lavoro per il quale si desidera visualizzare i dettagli.
... Nella pagina protezione/Dettagli lavoro, fare clic su *Aggiorna* per aggiornare l'elenco delle attività e i dettagli delle attività associati al lavoro di configurazione della protezione e per determinare quando il lavoro è completo. Al termine dei lavori, i trasferimenti di dati vengono ripristinati al successivo intervallo di trasferimento pianificato.





