---
permalink: online-help/task-importing-a-data-policy-configuration.html 
sidebar: sidebar 
keywords:  
summary: È possibile importare una configurazione di policy dei dati da un file, modificare la policy dei dati e quindi attivare le modifiche nella SVM con Infinite Volume. Ad esempio, in caso di disastro, è possibile importare un criterio dati già definito nel secondario e modificarlo in base alle esigenze. 
---
= Importazione di una configurazione di policy dei dati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile importare una configurazione di policy dei dati da un file, modificare la policy dei dati e quindi attivare le modifiche nella SVM con Infinite Volume. Ad esempio, in caso di disastro, è possibile importare un criterio dati già definito nel secondario e modificarlo in base alle esigenze.



== Prima di iniziare

È necessario disporre del ruolo di amministratore dello storage o amministratore dello storage di OnCommand.



== A proposito di questa attività

Quando si importa una configurazione del criterio dati, le regole esistenti vengono sovrascritte.

La scheda Data Policy (Policy dati) viene visualizzata solo per le SVM con Infinite Volume (volumi Infiniti).



== Fasi

. Nel riquadro di navigazione a sinistra, fare clic su *Health* > *SVM*.
. Nella pagina di inventario *Health/Storage Virtual Machines*, selezionare la SVM appropriata.
. Fare clic su *Data Policy*.
+
Viene visualizzato l'elenco delle regole nella policy dei dati per la SVM selezionata con volume infinito.

. Fare clic su *Importa*.
. Nella finestra di dialogo *Import Data Policy*, specificare il criterio dati che si desidera importare fornendo il percorso assoluto del file dei criteri dati.
. Fare clic su *Importa*.
. Fare clic su *Activate* (attiva) per attivare le regole importate nella SVM.

