---
permalink: online-help/task-moving-workloads-to-a-node-in-a-different-ha-pair.html 
sidebar: sidebar 
keywords:  
summary: È possibile utilizzare Unified Manager per identificare un aggregato su un nodo in una coppia ad alta disponibilità diversa che ha una capacità di performance libera maggiore rispetto alla coppia ha in cui i carichi di lavoro sono attualmente in esecuzione. Quindi, è possibile spostare i volumi selezionati negli aggregati della nuova coppia ha. 
---
= Spostamento dei carichi di lavoro in un nodo di una coppia ha diversa
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare Unified Manager per identificare un aggregato su un nodo in una coppia di ha (High Availability) diversa che ha una capacità di performance libera maggiore rispetto alla coppia di ha in cui i carichi di lavoro sono attualmente in esecuzione. Quindi, è possibile spostare i volumi selezionati negli aggregati della nuova coppia ha.



== Prima di iniziare

* È necessario disporre del ruolo di operatore, amministratore OnCommand o amministratore dello storage.
* Il cluster deve essere composto da almeno due coppie ha
+
Non è possibile utilizzare questo processo di correzione se nel cluster è presente una sola coppia ha.

* È necessario aver registrato i nomi dei due nodi della coppia ha che attualmente presentano un problema di performance.
* È necessario aver registrato la data e l'ora in cui i nodi hanno ricevuto l'evento di performance.
* È necessario aver registrato l'ID evento, ad esempio "`p-sdt-clus1-nod-6982`".
* Unified Manager deve aver raccolto e analizzato i dati delle performance per un mese o più.




== A proposito di questa attività

Lo spostamento di carichi di lavoro dalle performance elevate in un aggregato su un nodo con una maggiore capacità di performance libera consente ai carichi di lavoro su entrambi i nodi di funzionare in modo più efficiente. Questa procedura consente di identificare le seguenti risorse in modo da poter spostare i carichi di lavoro dalle performance elevate in un nodo con una capacità di performance più libera su una coppia ha diversa:

* I nodi di una coppia ha diversa sullo stesso cluster che hanno la massima capacità di performance libera
* Gli aggregati sui nuovi nodi che hanno la maggiore capacità di performance libera
* I volumi dalle performance più elevate sui nodi correnti




== Fasi

. Identificare i nodi che fanno parte di una coppia ha diversa sullo stesso cluster:
+
.. Nella pagina *Dettagli evento*, fare clic sul nome del cluster su cui risiedono i nodi.
+
I dettagli del cluster vengono visualizzati nella pagina Landing di Performance/Cluster.

.. Nella pagina *Riepilogo*, fare clic su *nodi* dal riquadro *oggetti gestiti*.
+
L'elenco dei nodi di questo cluster viene visualizzato nella pagina Performance/Nodes (prestazioni/nodi).

.. Annotare i nomi dei nodi che si trovano in diverse coppie ha rispetto alla coppia ha che attualmente presenta un problema di performance.


. Identificare un nodo della nuova coppia ha con la massima capacità di performance libera:
+
.. Nella pagina *Performance/Nodes*, fare clic sulla colonna *Performance Capacity used* per ordinare i nodi in base alla percentuale minima utilizzata.
+
In questo modo viene fornito un elenco dei nodi potenziali in cui è possibile spostare i carichi di lavoro.

.. Annotare il nome del nodo su una coppia ha diversa in cui si desidera spostare i carichi di lavoro.


. Identifica un aggregato sul nuovo nodo che ha la maggiore capacità di performance libera:
+
.. Nella pagina *prestazioni/nodi*, fare clic sul nodo.
+
I dettagli del nodo vengono visualizzati nella pagina Performance/Node Explorer (Esplora prestazioni/nodo).

.. Nel menu *Visualizza e confronta*, selezionare *aggregati su questo nodo*.
+
Gli aggregati su questo nodo vengono visualizzati nella griglia.

.. Fare clic sulla colonna *Performance Capacity used* (capacità di performance utilizzata) per ordinare gli aggregati in base ai dati meno utilizzati.
+
In questo modo viene fornito un elenco di potenziali aggregati in cui è possibile spostare i carichi di lavoro.

.. Annotare il nome dell'aggregato in cui si desidera spostare i carichi di lavoro.


. Identificare i carichi di lavoro dalle performance elevate dei nodi che hanno ricevuto l'evento:
+
.. Torna alla pagina dei dettagli *evento* per l'evento.
.. Nel campo *volumi interessati*, fare clic sul collegamento relativo al numero di volumi per il primo nodo.
+
Viene visualizzata la pagina Performance/Volumes (prestazioni/volumi) con un elenco filtrato dei volumi su quel nodo.

.. Fare clic sulla colonna *capacità totale* per ordinare i volumi in base allo spazio allocato più grande.
+
In questo modo viene visualizzato un elenco dei volumi potenziali che si desidera spostare.

.. Annotare i nomi dei volumi che si desidera spostare e i nomi degli aggregati correnti in cui risiedono.
.. Eseguire i passaggi 4c e 4d per il secondo nodo che faceva parte di questo evento per identificare anche i volumi che si desidera spostare da quel nodo.


. Sposta i volumi negli aggregati identificati come dotati di capacità di performance massima sul nuovo nodo.
+
È possibile eseguire l'operazione di spostamento utilizzando Gestione sistema di OnCommand, OnCommand Workflow Automation, comandi ONTAP o una combinazione di questi strumenti.





== Al termine

Dopo alcuni giorni, è possibile verificare se si stanno ricevendo lo stesso tipo di eventi da questo nodo o aggregato.
