---
permalink: online-help/task-retrying-a-failed-protection-job.html 
sidebar: sidebar 
keywords:  
summary: 'Una volta adottate le misure necessarie per correggere un processo di protezione non riuscito, è possibile utilizzare Riprova per eseguire nuovamente il processo. Il nuovo tentativo di un lavoro crea un nuovo lavoro utilizzando l"ID lavoro originale.' 
---
= Tentativo di nuovo di un processo di protezione non riuscito
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una volta adottate le misure necessarie per correggere un processo di protezione non riuscito, è possibile utilizzare *Riprova* per eseguire nuovamente il processo. Il nuovo tentativo di un lavoro crea un nuovo lavoro utilizzando l'ID lavoro originale.



== Prima di iniziare

È necessario disporre del ruolo di amministratore dello storage o amministratore dello storage di OnCommand.



== A proposito di questa attività

È possibile riprovare solo un processo non riuscito alla volta. Selezionando più di un lavoro, il pulsante *Riprova* viene disattivato. È possibile eseguire un nuovo processo solo per i job del tipo Configurazione protezione e relazione protezione.



== Fasi

. Nel riquadro di spostamento di sinistra, fare clic su *protezione* > *lavori*.
. Dall'elenco dei job, selezionare un singolo job di tipo operazione di configurazione di protezione o relazione di protezione non riuscita.
+
Il pulsante *Riprova* è attivato.

. Fare clic su *Riprova*.
+
Il lavoro viene riavviato.


