---
settings:
  name: OnCommand Unified Manager 9.5
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documenti di OnCommand Unified Manager 9.5
    url: "/index.html"
  - title: Note di rilascio
    url: "/release-notes.html"
  - title: Inizia subito
    entries:
    - title: Installazione rapida per VMware vSphere
      url: "/qsg-vapp.html"
    - title: Installazione rapida per Linux
      url: "/qsg-linux.html"
    - title: Installazione rapida per Windows
      url: "/qsg-windows.html"
  - section: install
  - section: config
  - section: online-help
  - section: performance-checker
  - section: health-checker
  - title: Note legali
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Inizia subito
    links:
    - title: Note di rilascio
      url: "/release-notes.html"
    - title: Installazione rapida per VMware vSphere
      url: qsg-vapp.html
    - title: Installazione rapida per Linux
      url: qsg-linux.html
    - title: Installazione rapida per Windows
      url: qsg-windows.html
  - title: Installare e configurare Unified Manager
    links:
    - title: Installazione e aggiornamento su sistemi VMware vSphere
      url: install/concept-installing-upgrading-and-removing-unified-manager-software-on-vmware-vsphere.html
    - title: Installazione e aggiornamento su sistemi Linux
      url: install/concept-install-upgrade-and-remove-unified-manager-software.html
    - title: Installazione e aggiornamento su sistemi Windows
      url: install/concept-installing-upgrading-and-removing-unified-manager-software.html
    - title: Configurare Unified Manager
      url: config/concept-configuring-unified-manager.html
  - title: Monitoraggio delle performance
    links:
    - title: Soglie di performance
      url: performance-checker/concept-managing-performance-thresholds.html
    - title: Performance del cluster
      url: performance-checker/concept-monitoring-cluster-performance-from-the-dashboard.html
  - title: Più risorse
    links:
    - title: Video di Unified Manager
      url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7mp3jFSg0IJgo3oeDQRY-Gl
    - title: Blog di Unified Manager
      url: https://www.netapp.com/blog/#q=active%20iq%20unified%20manager&t=Blogs&sort=%40publish-date-mktg%20descending&layout=card&f:@facet-language-mktg=[English]
    - title: Documentazione per la versione più recente di Unified Manager
      url: https://docs.netapp.com/us-en/active-iq-unified-manager/index.html
