---
settings:
  name: OnCommand Unified Manager 9.5
  downlevel: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documenti di OnCommand Unified Manager 9.5
    url: "/index.html"
  - title: Note di rilascio
    url: "/release-notes.html"
  - title: Inizia subito
    entries:
    - title: Installazione rapida per VMware vSphere
      url: "/qsg-vapp.html"
    - title: Installazione rapida per Linux
      url: "/qsg-linux.html"
    - title: Installazione rapida per Windows
      url: "/qsg-windows.html"
  - section: install
  - section: config
  - section: online-help
  - section: performance-checker
  - section: health-checker
  - title: Note legali
    url: "/legal-notices.html"
