---
permalink: performance-checker/task-identifying-victim-workloads-involved-in-a-performance-event.html 
sidebar: sidebar 
keywords:  
summary: 'In Unified Manager, è possibile identificare i carichi di lavoro dei volumi con la maggiore deviazione nel tempo di risposta (latenza) causata da un componente dello storage in conflitto. L"identificazione di questi carichi di lavoro consente di capire perché le applicazioni client che accedono a tali carichi di lavoro hanno registrato performance più lente del solito.' 
---
= Identificazione dei carichi di lavoro delle vittime coinvolti in un evento di performance dinamico
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In Unified Manager, è possibile identificare i carichi di lavoro dei volumi con la maggiore deviazione nel tempo di risposta (latenza) causata da un componente dello storage in conflitto. L'identificazione di questi carichi di lavoro consente di capire perché le applicazioni client che accedono a tali carichi di lavoro hanno registrato performance più lente del solito.



== Prima di iniziare

* È necessario disporre del ruolo di operatore, amministratore OnCommand o amministratore dello storage.
* Devono essere presenti eventi di performance dinamiche nuovi, riconosciuti o obsoleti.




== A proposito di questa attività

La pagina Dettagli evento visualizza un elenco dei carichi di lavoro definiti dall'utente e dal sistema, classificati in base alla deviazione più elevata nell'attività o nell'utilizzo del componente o più interessati dall'evento. I valori si basano sui picchi identificati da Unified Manager al momento del rilevamento e dell'ultima analisi dell'evento.



== Fasi

. Visualizzare la pagina *Dettagli evento* per visualizzare le informazioni relative all'evento.
. Nei grafici Workload Latency (latenza del carico di lavoro) e Workload Activity (attività del carico di lavoro), selezionare *vittime workload*.
. Posizionare il cursore sui grafici per visualizzare i principali carichi di lavoro definiti dall'utente che influiscono sul componente e il nome del carico di lavoro della vittima.

