---
permalink: health-checker/concept-how-annotation-rules-work-in-unified-manager.html 
sidebar: sidebar 
keywords:  
summary: 'Una regola di annotazione è un criterio definito per annotare gli oggetti di storage (volumi, cluster o macchine virtuali di storage). È possibile utilizzare gruppi di condizioni o condizioni per definire le regole di annotazione.' 
---
= Funzionamento delle regole di annotazione in Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Una regola di annotazione è un criterio definito per annotare gli oggetti di storage (volumi, cluster o macchine virtuali di storage (SVM)). È possibile utilizzare gruppi di condizioni o condizioni per definire le regole di annotazione.

* È necessario associare una regola di annotazione a un'annotazione.
* È necessario associare un tipo di oggetto per una regola di annotazione; è possibile associare un solo tipo di oggetto per una regola di annotazione.
* Unified Manager aggiunge o rimuove le annotazioni dagli oggetti di storage dopo ogni ciclo di monitoraggio o quando una regola viene creata, modificata, eliminata o riordinata.
* Una regola di annotazione può avere uno o più gruppi di condizioni e ciascun gruppo di condizioni può avere una o più condizioni.
* Gli oggetti di storage possono avere più annotazioni. Una regola di annotazione per una particolare annotazione può anche utilizzare annotazioni diverse nelle condizioni della regola per aggiungere un'altra annotazione agli oggetti già annotati.




== Condizioni

È possibile creare più gruppi di condizioni e ciascun gruppo di condizioni può avere una o più condizioni. È possibile applicare tutti i gruppi di condizioni definiti in una regola di annotazione di un'annotazione per annotare gli oggetti di storage.

Le condizioni all'interno di un gruppo di condizioni vengono eseguite utilizzando AND logico. Tutte le condizioni di un gruppo di condizioni devono essere soddisfatte. Quando si crea o si modifica una regola di annotazione, viene creata una condizione che applica, seleziona e annota solo gli oggetti di storage che soddisfano tutte le condizioni del gruppo Condition. È possibile utilizzare più condizioni all'interno di un gruppo di condizioni per limitare l'ambito degli oggetti di storage da annotare.

È possibile creare condizioni con oggetti di storage utilizzando i seguenti operandi e operatore e specificando il valore richiesto.

|===
| Tipo di oggetto storage | Operandi applicabili 


 a| 
Volume
 a| 
* Nome dell'oggetto
* Nome del cluster proprietario
* Nome SVM proprietario
* Annotazioni




 a| 
SVM
 a| 
* Nome dell'oggetto
* Nome del cluster proprietario
* Annotazioni




 a| 
Cluster
 a| 
* Nome dell'oggetto
* Annotazioni


|===
Quando si seleziona un'annotazione come operando per qualsiasi oggetto di storage, è disponibile l'operatore "`is`". Per tutti gli altri operandi, è possibile selezionare "`is`" o "`contains`" come operatore. Quando si seleziona l'operatore "`is`", la condizione viene valutata per una corrispondenza esatta del valore dell'operando con il valore fornito per l'operando selezionato. Quando si seleziona l'operatore "`contains`", la condizione viene valutata per soddisfare uno dei seguenti criteri:

* Il valore dell'operando corrisponde esattamente al valore dell'operando selezionato.
* Il valore dell'operando contiene il valore fornito per l'operando selezionato.




== Esempio di una regola di annotazione con condizioni

Prendere in considerazione una regola di annotazione con un gruppo di condizioni per un volume con le seguenti due condizioni:

* Il nome contiene "`vol`"
* Il nome SVM è "`dATA_svm`"


Questa regola di annotazione consente di annotare tutti i volumi che includono "`vol`" nei loro nomi e che sono ospitati sulle SVM con il nome "`data_svm`" con l'annotazione selezionata e il tipo di annotazione.



== Gruppi di condizioni

I gruppi di condizioni vengono eseguiti utilizzando OR logico e quindi applicati agli oggetti di storage. Gli oggetti di storage devono soddisfare i requisiti di uno dei gruppi di condizioni da annotare. Gli oggetti di storage che soddisfano le condizioni di tutti i gruppi di condizioni vengono annotati. È possibile utilizzare i gruppi di condizioni per aumentare l'ambito degli oggetti di storage da annotare.



== Esempio di una regola di annotazione con gruppi di condizioni

Prendere in considerazione una regola di annotazione con due gruppi di condizioni per un volume; ciascun gruppo contiene le seguenti due condizioni:

* Gruppo di condizioni 1
+
** Il nome contiene "`vol`"
** Il nome SVM è "`dATA_svm`". Questo gruppo di condizioni annoterà tutti i volumi che includono "`vol`" nei loro nomi e che sono ospitati sulle SVM con il nome "`dATA_svm`".


* Gruppo di condizioni 2
+
** Il nome contiene "`vol`"
** Il valore di annotazione della priorità dei dati è "`critico`". Questo gruppo di condizioni annoterà tutti i volumi che includono "`vol`" nei loro nomi e che sono annotati con il valore di annotazione della priorità dei dati come "`critico`".




Quando una regola di annotazione contenente questi due gruppi di condizioni viene applicata agli oggetti di storage, vengono annotati i seguenti oggetti di storage:

* Tutti i volumi che includono "`vol`" nei loro nomi e che sono ospitati su SVM con il nome "`data_svm`".
* Tutti i volumi che includono "`vol`" nei loro nomi e che sono annotati con il valore di annotazione data-priority come "`critical`".

