---
permalink: health-checker/reference-identity-provider-requirements-um.html 
sidebar: sidebar 
keywords:  
summary: 'Quando si configura Unified Manager per l"utilizzo di un provider di identità per l"autenticazione SAML per tutti gli utenti remoti, è necessario conoscere alcune impostazioni di configurazione necessarie per consentire la connessione a Unified Manager.' 
---
= Requisiti del provider di identità
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si configura Unified Manager per utilizzare un provider di identità (IdP) per eseguire l'autenticazione SAML per tutti gli utenti remoti, è necessario conoscere alcune impostazioni di configurazione necessarie per consentire la connessione a Unified Manager.

È necessario immettere l'URI e i metadati di Unified Manager nel server IdP. È possibile copiare queste informazioni dalla pagina autenticazione SAML di Unified Manager. Unified Manager è considerato il service provider (SP) nello standard SAML (Security Assertion Markup Language).



== Standard di crittografia supportati

* AES (Advanced Encryption Standard): AES-128 e AES-256
* Secure Hash Algorithm (SHA): SHA-1 e SHA-256




== Provider di identità validati

* Shibboleth
* Active Directory Federation Services (ADFS)




== Requisiti di configurazione di ADFS

* È necessario definire tre regole per le attestazioni nell'ordine seguente, necessarie affinché Unified Manager analizzi le risposte SAML di ADFS per questa voce di trust della parte che si basa.
+
|===
| Regola della richiesta di rimborso | Valore 


 a| 
Nome-account-SAM
 a| 
ID nome



 a| 
Nome-account-SAM
 a| 
urn:oid:0.9.2342.19200300.100.1.1



 a| 
Gruppi di token -- Nome non qualificato
 a| 
urn:oid:1.3.6.1.4.1.5923.1.5.1.1

|===
* È necessario impostare il metodo di autenticazione su "`Forms Authentication`" per consentire agli utenti di ricevere un errore durante la disconnessione da Unified Manager quando si utilizza Internet Explorer. Attenersi alla seguente procedura:
+
.. Aprire la console di gestione ADFS.
.. Fare clic sulla cartella Authentication Policies (Criteri di autenticazione) nella vista ad albero a sinistra.
.. Nella sezione azioni a destra, fare clic su Modifica policy di autenticazione primaria globale.
.. Impostare il metodo di autenticazione Intranet su "`Forms Authentication`" invece di "`Windows Authentication`" predefinito.


* In alcuni casi, l'accesso tramite IdP viene rifiutato quando il certificato di sicurezza di Unified Manager è firmato dalla CA. Esistono due soluzioni alternative per risolvere questo problema:
+
** Seguire le istruzioni indicate nel collegamento per disattivare il controllo di revoca sul server ADFS per la parte di base associata al certificato CA concatenato:
+
http://www.torivar.com/2016/03/22/adfs-3-0-disable-revocation-check-windows-2012-r2/[]

** Fare in modo che il server CA si trovi all'interno del server ADFS per firmare la richiesta di certificazione del server Unified Manager.






== Altri requisiti di configurazione

* L'inclinazione dell'orologio di Unified Manager è impostata su 5 minuti, quindi la differenza di tempo tra il server IdP e il server Unified Manager non può superare i 5 minuti o l'autenticazione non riesce.
* Quando gli utenti tentano di accedere a Unified Manager utilizzando Internet Explorer, potrebbe essere visualizzato il messaggio *il sito Web non può visualizzare la pagina*. In questo caso, assicurarsi che questi utenti deselezionino l'opzione "`Show friendly HTTP error messages`" (Visualizza messaggi di errore HTTP descrittivi) in *Tools* > *Internet Options* > *Advanced* (Strumenti* > *Opzioni Internet* > *Avanzate*).

