---
permalink: health-checker/task-creating-a-snapvault-protection-relationship-from-the-health-volume-details-page.html 
sidebar: sidebar 
keywords:  
summary: È possibile creare una relazione SnapVault utilizzando la pagina dei dettagli di integrità/volume in modo che i backup dei dati siano abilitati per scopi di protezione sui volumi. 
---
= Creazione di una relazione di protezione SnapVault dalla pagina dei dettagli di salute/volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare una relazione SnapVault utilizzando la pagina dei dettagli di integrità/volume in modo che i backup dei dati siano abilitati per scopi di protezione sui volumi.



== Prima di iniziare

* È necessario disporre del ruolo di amministratore dello storage o amministratore dello storage di OnCommand.
* Per eseguire questa attività, è necessario aver impostato l'automazione del flusso di lavoro.




== A proposito di questa attività

Il menu *Protect* non viene visualizzato nelle seguenti istanze:

* Se le impostazioni RBAC non consentono questa azione: Ad esempio, se si dispone solo di privilegi operatore
* Quando l'ID del volume è sconosciuto: Ad esempio, quando si dispone di una relazione tra cluster e il cluster di destinazione non è stato ancora rilevato




== Fasi

. Nella scheda *Protection* della pagina dei dettagli *Health/Volume*, fare clic con il pulsante destro del mouse su un volume nella vista della topologia che si desidera proteggere.
. Selezionare *Protect* > *SnapVault* dal menu.
+
Viene visualizzata la finestra di dialogo Configura protezione.

. Fare clic su *SnapVault* per visualizzare la scheda *SnapVault* e configurare le informazioni sulle risorse secondarie.
. Fare clic su *Advanced* (Avanzate) per impostare deduplica, compressione, crescita automatica e garanzia di spazio secondo necessità, quindi fare clic su *Apply* (Applica).
. Completare l'area *Destination Information* (informazioni destinazione) e l'area *Relationship Settings* (Impostazioni relazione) nella finestra di dialogo *Configure Protection* (Configura protezione).
. Fare clic su *Apply* (Applica).
+
Viene visualizzata nuovamente la pagina Health/Volume Details (Dettagli salute/volume).

. Fare clic sul collegamento al processo di configurazione della protezione nella parte superiore della pagina dei dettagli *Health/Volume*.
+
Viene visualizzata la pagina protezione/Dettagli lavoro.

. Fare clic su *Refresh* (Aggiorna) per aggiornare l'elenco delle attività e i dettagli delle attività associati al processo di configurazione della protezione e per determinare quando il processo è completo.
+
Una volta completate le attività di lavoro, le nuove relazioni vengono visualizzate nella vista topologia della pagina Health/Volume Details.


