---
permalink: health-checker/task-resolving-capacity-issues.html 
sidebar: sidebar 
keywords:  
summary: Questo flusso di lavoro fornisce un esempio di come risolvere un problema di capacità. In questo scenario, si è un amministratore o un operatore e si accede alla pagina Dashboard/Panoramica di Unified Manager per verificare se uno degli oggetti di storage monitorati presenta problemi di capacità. Si vede che esiste un volume con un rischio di capacità e si desidera determinare la possibile causa del problema e risolverlo. 
---
= Risoluzione dei problemi di capacità
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Questo flusso di lavoro fornisce un esempio di come risolvere un problema di capacità. In questo scenario, si è un amministratore o un operatore e si accede alla pagina Unified ManagerDashboards/Overview per verificare se uno degli oggetti di storage monitorati presenta problemi di capacità. Si vede che esiste un volume con un rischio di capacità e si desidera determinare la possibile causa del problema e risolverlo.



== Prima di iniziare

È necessario disporre del ruolo di operatore, amministratore OnCommand o amministratore dello storage.



== A proposito di questa attività

Nella pagina Dashboards/Overview, esaminare l'area Unresolved Incidents and Risks (incidenti e rischi non risolti) e visualizzare un evento di errore "`Volume Space Full`" (spazio volume pieno) nel riquadro Capacity (capacità) sotto SVM Volume Capacity at Risk (capacità volume SVM a rischio)



== Fasi

. Nell'area *incidenti e rischi non risolti* della pagina *Dashboards/Overview*, fare clic sul nome dell'evento di errore Volume Space Full nel riquadro *Capacity*.
+
Viene visualizzata la pagina Dettagli evento relativa all'errore.

. Dalla pagina dei dettagli *evento*, è possibile eseguire una o più delle seguenti attività:
+
** Esaminare il messaggio di errore nel campo cause (causa) e fare clic sui suggerimenti nella sezione Suggested Remedial Actions (azioni correttive suggerite) per esaminare le descrizioni delle possibili soluzioni. xref:task-performing-suggested-remedial-actions-for-a-full-volume.adoc[Esecuzione delle azioni correttive suggerite per un volume completo]
** Fare clic sul nome dell'oggetto, in questo caso un volume, nel campo Source (origine) per ottenere i dettagli sull'oggetto. xref:reference-health-volume-details-page.adoc[Pagina dei dettagli sul volume]
** Cercare le note che potrebbero essere state aggiunte a questo evento. xref:task-adding-and-reviewing-notes-about-an-event.adoc[Aggiunta e revisione di note associate a un evento]
** Aggiungere una nota all'evento. xref:task-adding-and-reviewing-notes-about-an-event.adoc[Aggiunta e revisione di note associate a un evento]
** Assegnare l'evento a un altro utente. xref:task-assigning-events-to-specific-users.adoc[Assegnazione di eventi]
** Riconoscere l'evento. xref:task-acknowledging-and-resolving-events.adoc[Riconoscimento e risoluzione degli eventi]
** Contrassegnare l'evento come risolto. xref:task-acknowledging-and-resolving-events.adoc[Riconoscimento e risoluzione degli eventi]



