---
permalink: health-checker/task-creating-a-new-mysql-data-set-using-birt.html 
sidebar: sidebar 
keywords:  
summary: 'Dopo aver creato l"origine dati, è necessario creare un set di dati MySQL per creare i risultati di output per il report. È inoltre possibile modificare i tipi di output dopo aver creato il set di dati.' 
---
= Creazione di un nuovo set di dati MySQL con BIRT
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver creato l'origine dati, è necessario creare un set di dati MySQL per creare i risultati di output per il report. È inoltre possibile modificare i tipi di output dopo aver creato il set di dati.



== Prima di iniziare

È necessario aver creato un'origine dati JDBC utilizzando BIRT.

È necessario aver scaricato e installato MySQL Connector/J.

È necessario aver creato un utente di database con il ruolo Schema report in Unified Manager.



== Fasi

. Da *Eclipse*, selezionare un'area di lavoro.
. Selezionare *Esplora dati* > *Set di dati* > *nuovo set di dati*.
. Nella finestra di dialogo *nuovo set di dati*, selezionare l'origine dati precedentemente creata, il tipo di set di dati e il nome del set di dati, quindi fare clic su *Avanti*.
. Definire un testo di query SQL utilizzando gli elementi disponibili oppure inserire manualmente la query e fare clic su *fine*.
. Fare clic su *Preview Results* (Anteprima risultati) per confermare la query SQL, quindi fare clic su *OK*.
. Nella finestra di dialogo *Edit Data Set* (Modifica set di dati), definire le colonne di output in base alle necessità e fare clic su *OK*.
. Trascinare gli elementi nel report appena creato.




== Al termine

A questo punto, è necessario importare il report appena creato in Unified Manager.
