---
permalink: health-checker/task-changing-the-maintenance-user-password-on-windows.html 
sidebar: sidebar 
keywords:  
summary: Se necessario, è possibile modificare la password utente per la manutenzione di Unified Manager. 
---
= Modifica della password utente per la manutenzione in Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se necessario, è possibile modificare la password utente per la manutenzione di Unified Manager.



== Fasi

. Dalla pagina di accesso all'interfaccia utente Web di Unified Manager, fare clic su *Password dimenticata*.
+
Viene visualizzata una pagina che richiede il nome dell'utente di cui si desidera reimpostare la password.

. Inserire il nome utente e fare clic su *Submit* (Invia).
+
Un'e-mail con un collegamento per reimpostare la password viene inviata all'indirizzo e-mail definito per tale nome utente.

. Fare clic sul collegamento *reset password* nell'e-mail e definire la nuova password.
. Tornare all'interfaccia utente Web e accedere a Unified Manager utilizzando la nuova password.




== Al termine

Se Unified Manager è installato in un ambiente Microsoft Cluster Server (MSCS), è necessario modificare la password utente di manutenzione sul secondo nodo dell'installazione di MSCS. La password utente di manutenzione per entrambi i nodi deve essere la stessa.
