---
permalink: config/task-adding-clusters.html 
sidebar: sidebar 
keywords:  
summary: È possibile aggiungere un cluster a Gestione unificata di OnCommand in modo da poter monitorare il cluster. Ciò include la possibilità di ottenere informazioni sul cluster, come lo stato di salute, la capacità, le performance e la configurazione del cluster, in modo da individuare e risolvere eventuali problemi che potrebbero verificarsi. 
---
= Aggiunta di cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile aggiungere un cluster a Gestione unificata di OnCommand in modo da poter monitorare il cluster. Ciò include la possibilità di ottenere informazioni sul cluster, come lo stato di salute, la capacità, le performance e la configurazione del cluster, in modo da individuare e risolvere eventuali problemi che potrebbero verificarsi.



== Prima di iniziare

* È necessario disporre del ruolo di amministratore dello storage o amministratore dello storage di OnCommand.
* È necessario disporre delle seguenti informazioni:
+
** Nome host o indirizzo IP di gestione del cluster
+
Il nome host è l'FQDN o il nome breve utilizzato da Unified Manager per connettersi al cluster. Il nome host deve essere risolto nell'indirizzo IP di gestione del cluster.

+
L'indirizzo IP di gestione del cluster deve essere la LIF di gestione del cluster della SVM (Administrative Storage Virtual Machine). Se si utilizza una LIF di gestione dei nodi, l'operazione non riesce.

** Nome utente e password dell'amministratore di Data ONTAP
+
Questo account deve avere il ruolo _admin_ con l'accesso dell'applicazione impostato su _ontapi_, _ssh_ e _http_.

** Tipo di protocollo (HTTP o HTTPS) che è possibile configurare sul cluster e numero di porta utilizzato per la connessione al cluster


+
[NOTE]
====
È possibile aggiungere cluster protetti da NAT/firewall utilizzando l'indirizzo IP NAT di Unified Manager. Tutti i sistemi di automazione del flusso di lavoro o SnapProtect collegati devono essere protetti da NAT/firewall e le chiamate API SnapProtect devono utilizzare l'indirizzo IP NAT per identificare il cluster.

====
* L'FQDN di Unified Manager deve essere in grado di eseguire il ping del sistema ONTAP.
+
È possibile verificarlo utilizzando il seguente comando ONTAP: `ping -node node_name -destination Unified_Manager_FQDN`.

* È necessario disporre di spazio sufficiente sul server Unified Manager. Non è possibile aggiungere un cluster al server quando più del 90% dello spazio nella directory del database è già occupato.




== A proposito di questa attività

Per una configurazione MetroCluster, è necessario aggiungere i cluster locali e remoti e i cluster devono essere configurati correttamente.

È possibile monitorare un singolo cluster mediante due istanze di Unified Manager, a condizione che sia stata configurata una seconda LIF di gestione del cluster sul cluster in modo che ogni istanza di Unified Manager si connetta attraverso una LIF diversa.



== Fasi

. Nel riquadro di navigazione a sinistra, fare clic su *Configuration* > *Cluster Data Sources*.
. Nella pagina *Configuration/Cluster Data Sources* (origini dati cluster/configurazione), fare clic su *Add* (Aggiungi).
. Nella finestra di dialogo *Aggiungi cluster*, specificare i valori richiesti, ad esempio il nome host o l'indirizzo IP del cluster, il nome utente, la password, il protocollo di comunicazione e il numero di porta.
+
Per impostazione predefinita, sono selezionati il protocollo HTTPS e la porta 443.

+
È possibile modificare l'indirizzo IP di gestione del cluster da IPv6 a IPv4 o da IPv4 a IPv6. Il nuovo indirizzo IP viene visualizzato nella griglia del cluster e nella pagina di configurazione del cluster al termine del successivo ciclo di monitoraggio.

. Fare clic su *Invia*.
. Se si seleziona HTTPS, attenersi alla seguente procedura:
+
.. Nella finestra di dialogo *Authorize host* (autorizza host), fare clic su *View Certificate* (Visualizza certificato) per visualizzare le informazioni sul certificato del cluster.
.. Fare clic su *Sì*.
+
Unified Manager controlla il certificato solo quando il cluster viene aggiunto inizialmente. Unified Manager non controlla il certificato per ogni chiamata API a ONTAP.

+
Se il certificato è scaduto, non è possibile aggiungere un nuovo cluster. È necessario prima rinnovare il certificato SSL e quindi aggiungere il cluster.







== Risultati

Una volta individuati tutti gli oggetti di un nuovo cluster (circa 15 minuti), Unified Manager inizia a raccogliere dati storici sulle performance per i 15 giorni precedenti. Queste statistiche vengono raccolte utilizzando la funzionalità di raccolta della continuità dei dati. Questa funzionalità fornisce oltre due settimane di informazioni sulle performance per un cluster subito dopo l'aggiunta. Una volta completato il ciclo di raccolta della continuità dei dati, i dati delle performance del cluster in tempo reale vengono raccolti, per impostazione predefinita, ogni cinque minuti.

[NOTE]
====
Dato che la raccolta di 15 giorni di dati sulle performance richiede un uso intensivo della CPU, si consiglia di eseguire l'aggiunta di nuovi cluster in modo che i sondaggi per la raccolta della continuità dei dati non vengano eseguiti su troppi cluster contemporaneamente. Inoltre, se si riavvia Unified Manager durante il periodo di raccolta della continuità dei dati, la raccolta viene interrotta e vengono visualizzate lacune nei grafici delle performance per il periodo di tempo mancante.

====
[TIP]
====
Se viene visualizzato un messaggio di errore che indica che non è possibile aggiungere il cluster, controllare se si verificano i seguenti problemi:

* Se gli orologi dei due sistemi non sono sincronizzati e la data di inizio del certificato HTTPS di Unified Manager è successiva alla data sul cluster. È necessario assicurarsi che gli orologi siano sincronizzati utilizzando NTP o un servizio simile.
* Se il cluster ha raggiunto il numero massimo di destinazioni di notifica EMS, l'indirizzo di Unified Manager non può essere aggiunto. Per impostazione predefinita, nel cluster è possibile definire solo 20 destinazioni di notifica EMS.


====