---
permalink: install/task-upgrading-unified-manager-vapp.html 
sidebar: sidebar 
keywords:  
summary: 'È possibile eseguire l"aggiornamento a Unified Manager versione 9.5 solo dalle istanze di Unified Manager 7.3 o 9.4.' 
---
= Aggiornamento di Unified Manager su VMware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire l'aggiornamento a Unified Manager versione 9.5 solo dalle istanze di Unified Manager 7.3 o 9.4.



== A proposito di questa attività

Durante il processo di aggiornamento, Unified Manager non è disponibile. Prima di eseguire l'aggiornamento di Unified Manager, è necessario completare tutte le operazioni in esecuzione.

Se Unified Manager è associato a un'istanza di OnCommand Workflow Automation e sono disponibili nuove versioni del software per entrambi i prodotti, è necessario scollegare i due prodotti e impostare una nuova connessione per l'automazione del flusso di lavoro dopo aver eseguito gli aggiornamenti. Se si esegue un aggiornamento a uno solo dei prodotti, dopo l'aggiornamento è necessario accedere a Workflow Automation e verificare che stia ancora acquisendo dati da Unified Manager.
