---
permalink: install/task-changing-the-jboss-password.html 
sidebar: sidebar 
keywords:  
summary: 'È possibile creare una nuova password JBoss personalizzata per sovrascrivere la password predefinita impostata durante l"installazione. Questa attività è facoltativa, ma alcuni siti potrebbero richiedere questa funzionalità di protezione per sovrascrivere l"impostazione predefinita di installazione di Unified Manager. Questa operazione modifica anche la password utilizzata da JBoss per accedere a MySQL.' 
---
= Modifica della password JBoss
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare una nuova password JBoss personalizzata per sovrascrivere la password predefinita impostata durante l'installazione. Questa attività è facoltativa, ma alcuni siti potrebbero richiedere questa funzionalità di protezione per sovrascrivere l'impostazione predefinita di installazione di Unified Manager. Questa operazione modifica anche la password utilizzata da JBoss per accedere a MySQL.



== Prima di iniziare

* È necessario disporre dell'accesso utente root al sistema Red Hat Enterprise Linux o CentOS su cui è installato Unified Manager.
* Devi essere in grado di accedere al servizio fornito da NetApp `password.sh` script nella directory `/opt/netapp/essentials/bin`.




== Fasi

. Accedere come utente root sul sistema.
. Arrestare i servizi di Unified Manager immettendo i seguenti comandi nell'ordine indicato: `service ocieau stop``service ocie stop`
+
Non interrompere il software MySQL associato.

. Immettere il seguente comando per avviare il processo di modifica della password: `/opt/netapp/essentials/bin/password.sh resetJBossPassword`
. Quando richiesto, inserire la vecchia password JBoss.
+
La password predefinita è `D11h1aMu@79%`.

. Quando richiesto, inserire la nuova password JBoss, quindi immetterla una seconda volta per confermarla.
. Al termine dello script, avviare i servizi di Unified Manager immettendo i seguenti comandi nell'ordine indicato: `service ocie start``service ocieau start`
. Una volta avviati tutti i servizi, è possibile accedere all'interfaccia utente di Unified Manager.

