---
permalink: install/task-upgrading-mysql-on-windows-ocum.html 
sidebar: sidebar 
keywords: OnCommand Unified Manager 
summary: 'È possibile eseguire l"aggiornamento a una versione più recente di MySQL sul server Windows su cui è installato Unified Manager per ottenere correzioni per le vulnerabilità della sicurezza.' 
---
= Aggiornamento di MySQL su Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire l'aggiornamento a una versione più recente di MySQL sul server Windows su cui è installato Unified Manager per ottenere correzioni per le vulnerabilità della sicurezza.



== Prima di iniziare

* È necessario disporre dei privilegi di amministratore di Windows per il sistema su cui è installato Unified Manager.
* Devi avere la password per l'utente root MySQL.




== Fasi

. Accedere come utente amministratore sul computer host di Unified Manager.
. Scarica la versione appropriata di MySQL sul sistema di destinazione.
. Utilizzare la console dei servizi Windows per arrestare i seguenti servizi di Unified Manager:
+
** NetApp OCIE Acquisition Unit (Ocie-au)
** Server applicativo NetApp OnCommand (Oncommandsvc)
** MYSQL


. Fare clic su `.msi` Pacchetto per richiamare l'aggiornamento di MySQL e seguire le istruzioni sullo schermo per completare l'aggiornamento.
. Avviare i servizi di Unified Manager utilizzando la console dei servizi Windows:
+
** MYSQL
** Server applicativo NetApp OnCommand (Oncommandsvc)
** NetApp OCIE Acquisition Unit (Ocie-au)



