---
permalink: install/task-selinux-requirements-for-mounting-opt-netapp-or-opt-netapp-data-on-an-nfs-or-cifs-share.html 
sidebar: sidebar 
keywords: Unified Manager 
summary: 'Se si intende montare /opt/netapp o /opt/netapp/data su un dispositivo NAS o SAN e si dispone dell"opzione SELinux attivata, è necessario tenere presente le seguenti considerazioni.' 
---
= Requisiti SELinux per il montaggio di /opt/netapp o /opt/netapp/data su una condivisione NFS o CIFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se si prevede di montare `/opt/netapp` oppure `/opt/netapp/data` Su un dispositivo NAS o SAN e se SELinux è attivato, è necessario tenere presente le seguenti considerazioni.



== A proposito di questa attività

Se stanno pianificando il montaggio `/opt/netapp` oppure `/opt/netapp/data` Da qualsiasi altro punto del file system root e se SELinux è abilitato nel proprio ambiente, è necessario impostare il contesto corretto per le directory montate. Seguire questi due passaggi per impostare e confermare il contesto SELinux corretto.

* Configurare il contesto SELinux quando `/opt/netapp/data` è montato
* Configurare il contesto SELinux quando `/opt/netapp` è montato


*Configurazione del contesto SELinux quando `/opt/netapp/data` è montato*

Se è stato montato `/opt/netapp/data` Nel sistema e SELinux è impostato su `Enforcing`, Assicurarsi che il tipo di contesto SELinux per `/opt/netapp/data` è impostato su `mysqld_db_t`, che è l'elemento di contesto predefinito per la posizione dei file di database.

. Eseguire questo comando per verificare il contesto: `ls -dZ /opt/netapp/data`
+
Un output di esempio:

+
[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:default_t:s0 /opt/netapp/data
----
+
In questo output, il contesto è `default_t` questo deve essere modificato in `mysqld_db_t`.

. Eseguire questa procedura per impostare il contesto, in base al modo in cui è stato montato `/opt/netapp/data`.
+
.. Eseguire i seguenti comandi per impostare il contesto su `mysqld_db_t`: `semanage fcontext -a -t mysql_db_t "/opt/netapp/data"``restorecon -R -v /opt/netapp/data`
.. Se è stato configurato `/opt/netapp/data` poll `/etc/fstab`, è necessario modificare `/etc/fstab` file. Per `/opt/netapp/data/` Montare l'opzione, aggiungere l'etichetta MySQL come: `context=system_u:object_r:mysqld_db_t:s0`
.. Smontare e rimontare `/opt/netapp/data/` per abilitare il contesto.
.. Se si dispone di un mount NFS diretto, eseguire il seguente comando per impostare il contesto su `mysql_db_t`: `mount <nfsshare>:/<mountpoint> /opt/netapp/data -o context=system_u:object_r:mysql_db_t:s0`


. Verificare che il contesto sia impostato correttamente: `ls -dZ /opt/netapp/data/`
+
[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:mysqld_db_t:s0 /opt/netapp/data/
----


*Configurazione del contesto SELinux quando `/opt/netapp` è montato*

Dopo aver impostato il contesto corretto per `/opt/netapp/data/`, assicurarsi che la directory principale `/opt/netapp` Il contesto SELinux non è impostato su `file_t`.

. Eseguire questo comando per verificare il contesto: `ls -dZ /opt/netapp`
+
Un output di esempio:

+
[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:file_t:s0 /opt/netapp
----
+
In questo output, il contesto è `file_t` questo va modificato. I seguenti comandi impostano il contesto su `usr_t`. È possibile impostare il contesto su un valore diverso da `file_t` in base ai tuoi requisiti di sicurezza.

. Eseguire questa procedura per impostare il contesto, in base al modo in cui è stato montato `/opt/netapp`.
+
.. Eseguire i seguenti comandi per impostare il contesto: `semanage fcontext -a -t usr_t "/opt/netapp"``restorecon -v /opt/netapp`
.. Se è stato configurato `/opt/netapp` poll `/etc/fstab`, è necessario modificare `/etc/fstab` file. Per `/opt/netapp` Montare l'opzione, aggiungere l'etichetta MySQL come: `context=system_u:object_r:usr_t:s0`
.. Smontare e rimontare `/opt/netapp` per abilitare il contesto.
.. Se si dispone di un mount NFS diretto, eseguire il seguente comando per impostare il contesto: `mount <nfsshare>:/<mountpoint> /opt/netapp -o context=system_u:object_r:usr_t:s0`


. Verificare che il contesto sia impostato correttamente: `ls -dZ /opt/netapp`
+
[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:usr_t:s0 /opt/netapp
----

